# Generated by Django 3.1.5 on 2021-01-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='time',
            field=models.TextField(null=True),
        ),
    ]
